export type Continent = "americas" | "europe" | "asia";

// Matches the 3-way "Battle of 3 Continents" framing used elsewhere on the
// site (Asia bucket absorbs APAC/MEA, same split used in the internal ops
// doc). Countries not listed here (e.g. "XX" / Other) are simply excluded
// from the "countries already in the race" block.
export const CONTINENT_BY_COUNTRY: Record<string, Continent> = {
  // Americas
  US: "americas",
  CA: "americas",
  MX: "americas",
  BR: "americas",
  AR: "americas",
  CL: "americas",
  CO: "americas",
  PE: "americas",
  EC: "americas",
  UY: "americas",
  PY: "americas",
  BO: "americas",
  VE: "americas",
  PA: "americas",
  CR: "americas",
  GT: "americas",
  HN: "americas",
  SV: "americas",
  NI: "americas",
  DO: "americas",
  PR: "americas",
  CU: "americas",
  JM: "americas",
  TT: "americas",
  BS: "americas",
  BB: "americas",

  // Europe
  FR: "europe",
  GB: "europe",
  DE: "europe",
  ES: "europe",
  PT: "europe",
  IT: "europe",
  NL: "europe",
  BE: "europe",
  CH: "europe",
  AT: "europe",
  IE: "europe",
  LU: "europe",
  SE: "europe",
  NO: "europe",
  DK: "europe",
  FI: "europe",
  IS: "europe",
  PL: "europe",
  CZ: "europe",
  SK: "europe",
  HU: "europe",
  RO: "europe",
  BG: "europe",
  GR: "europe",
  HR: "europe",
  SI: "europe",
  RS: "europe",
  UA: "europe",
  EE: "europe",
  LV: "europe",
  LT: "europe",
  MT: "europe",
  CY: "europe",
  RU: "europe",

  // Asia / APAC / MEA
  CN: "asia",
  JP: "asia",
  KR: "asia",
  IN: "asia",
  ID: "asia",
  TH: "asia",
  VN: "asia",
  PH: "asia",
  MY: "asia",
  SG: "asia",
  TW: "asia",
  HK: "asia",
  PK: "asia",
  BD: "asia",
  LK: "asia",
  NP: "asia",
  KH: "asia",
  LA: "asia",
  MM: "asia",
  MN: "asia",
  KZ: "asia",
  UZ: "asia",
  AE: "asia",
  SA: "asia",
  QA: "asia",
  KW: "asia",
  BH: "asia",
  OM: "asia",
  JO: "asia",
  LB: "asia",
  IL: "asia",
  TR: "asia",
  EG: "asia",
  MA: "asia",
  DZ: "asia",
  TN: "asia",
  ZA: "asia",
  NG: "asia",
  KE: "asia",
  GH: "asia",
  ET: "asia",
  SN: "asia",
  CI: "asia",
  CM: "asia",
  UG: "asia",
  TZ: "asia",
  RW: "asia",
  AU: "asia",
  NZ: "asia",
  FJ: "asia",
  GE: "asia",
  AM: "asia",
  AZ: "asia",
};

export const CONTINENT_LABELS: Record<Continent, string> = {
  americas: "Americas",
  europe: "Europe",
  asia: "Asia",
};

// Renders a flag emoji from a 2-letter ISO country code — no image assets
// to source or host.
export function flagEmoji(countryCode: string): string {
  const code = countryCode.toUpperCase();
  if (code.length !== 2) return "🏳️";
  const points = [...code].map((c) => 127397 + c.charCodeAt(0));
  return String.fromCodePoint(...points);
}
